baseURL = "https://yuzu.legal/"
languageCode = "en-us"
title = "Yuzu - Innovative Legal Solutions"
theme = "ananke"

[build]
  hugo-version = "0.92.0"

# Site parameters
[params]
  favicon = "/images/favicon.ico"
  site_logo = "/images/yuzu-logo.png"
  description = "Yuzu offers Managed Legal Services, Fractional GCs, Contract Lawyers, and Legal Ops Consulting"
  facebook = ""
  twitter = "https://twitter.com/YuzuLegal"
  instagram = ""
  youtube = ""
  github = ""
  linkedin = "https://www.linkedin.com/company/yuzu-legal/"
  background_color_class = "bg-gray-100"
  featured_image = "/images/yuzu-hero.jpg"
  recent_posts_number = 3
  custom_css = ["/css/custom.css"]
  body_classes = "avenir bg-near-white"
  post_content_classes = "avenir bg-near-white"
  custom_js = ["https://kit.fontawesome.com/your-fontawesome-kit.js"]

# Menu configuration
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Services"
    url = "/services/"
    weight = 2
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 4
